---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2021
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

name: Check Tinkerbell installation
# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - 'tinkerbell/*'

jobs:
  check-tinkerbell:
    name: Check Tinkerbell installation in an Ubuntu Bionic Virtual Environment
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Deploy services
        run: |
          cd tinkerbell/
          ./install.sh
          ./setup.sh
          ./deploy.sh
