---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2021
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

name: Check Tinkerbell installation
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - 'master'

jobs:
  check:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Tinkerbell dependencies
        run: cd tinkerbell/; ./install.sh
      - name: Setup Tinkerbell configuration
        run: cd tinkerbell/; ./setup.sh
      - name: Deploy Tinkerbell services
        run: cd tinkerbell/; ./deploy.sh
